## Discussion Section : Week 2

In [19]:
# Import libraries
import pandas as pd

In [20]:
# Read in data 
df = pd.read_csv("../data/Colorado_River_Basin_Water_Conflict_Table.csv")

### Preliminary Data Exploration

In [23]:
# Set pandas to display all columns in the dataframe 

pd.set_option("display.max_columns", None)
df

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,264,USGS301-350.docx,The Durango Herald (Colorado),Water officials consider action for worst case...,False,9-Jun-09,2019.0,6,NaN,6.0,2019.0,N,Y,Colorado Headwaters,140100,14,"Western Slope, CO",NaN,NaN,CO,8,Both,Water rights more generally,Board members of the Southwestern Waer Conserv...,"NGO, Conservation District, Agriculture, Business",0.0,Scored based on the fact that the discussion w...,NaN,0,0,3,3,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
264,265,USGS301-350.docx,"Rio Blanco Herald Times (Meeker, Colorado)",Rangely hosts Colorado River District event,False,21-Apr-22,2022.0,4/13/2022,13.0,4.0,2022.0,N,Y,Entire Colorado River Basin,NaN,"14, 15","Western Slope, CO",NaN,NaN,CO,8,Both,Drought; Water quality; Water rights more gene...,The event is a 'State of the River' event invo...,"Conservancy District, State Government, All Wa...",0.0,No true conflicts explored at this event. Pure...,NaN,2,1,5,0,0,0,0,1,0,0,3,0,0,0,0,1,1,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,AZ; CA,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
266,267,USGS301-350.docx,The Salt Lake Tribune,Scientists want to flush water past Glen Canyo...,False,13-Dec-07,2007.0,12,NaN,12.0,2007.0,N,N,Entire Colorado River Basin,NaN,"14, 15","Glen Canyon Dam, AZ",NaN,NaN,AZ,4,Both,Conservation,Dept of Interior Secretary Dirk Kempthorne sig...,"All Water Users, Environment",5.0,Scored 5 based on the agreement to protect the...,NaN,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0
267,268,USGS301-350.docx,Casa Grande Dispatch (AZ),Arizona plan could devastate Pinal farmers,NaN,2-Feb-19,2019.0,1/31/2019,31.0,1.0,2019.0,N,Y,Entire Colorado River Basin,NaN,"14, 15",State of Arizona,NaN,NaN,AZ,4,Both,Conservation; Ground water depletion,The event is Arizona signing off on the Drough...,"Agriculture, State Government, Federal Government",4.0,Agreement signed and cooperation on all sides...,NaN,1,0,0,10,0,0,0,1,0,0,2,0,0,0,0,0,0,0,0,0

In [25]:
# Use pandas methods to obtain preliminary information 
# and explore this data frame in at least four different ways.


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Event                                         268 non-null    int64
 1   Search Source                                 268 non-null    object
 2   Newspaper                                     268 non-null    object
 3   Article Title                                 268 non-null    object
 4   Duplicate                                     267 non-null    object
 5   Report Date                                   267 non-null    object
 6   Report Year                                   265 non-null    float64
 7   Event Date                                    248 non-null    object
 8   Event Day                                     18 non-null     float64
 9   Event Month                                   212 non-null    float64
 10  Event Year                                    257 non-null    float64
 11  Conflict Present                              252 non-null    object
 12  Crisis Present                                254 non-null    object
 13  Basin                                         250 non-null    object
 14  HUC6                                          110 non-null    object
 15  HUC2                                          250 non-null    object
 16  Place                                         254 non-null    object
 17  County                                        8 non-null      object
 18  County FIPS                                   8 non-null      float64
 19  State                                         178 non-null    object
 20  State FIPS                                    178 non-null    object
 21  Urban or Rural                                254 non-null    object
 22  Issue Type                                    255 non-null    object
 23  Event Summary                                 256 non-null    object
 24  Stakeholders                                  255 non-null    object
 25  Intensity Value                               255 non-null    float64
 26  Comments                                      190 non-null    object
 27  Related Observation Themes                    86 non-null     object
 28  Article Text Search - water quality           268 non-null    int64
 29  Article Text Search - invasive species        268 non-null    int64
 30  Article Text Search - conservation            268 non-null    int64
 31  Article Text Search - drought                 268 non-null    int64
 32  Article Text Search - flood                   268 non-null    int64
 33  Article Text Search - ground water depletion  268 non-null    int64
 34  Article Text Search - depletion               268 non-null    int64
 35  Article Text Search - infrastructure          268 non-null    int64
 36  Article Text Search - fish passage            268 non-null    int64
 37  Article Text Search - instream water rights   268 non-null    int64
 38  Article Text Search - water rights            268 non-null    int64
 39  Article Text Search - intergovernmental       268 non-null    int64
 40  Article Text Search - water transfers         268 non-null    int64
 41  Article Text Search - navigation              268 non-null    int64
 42  Article Text Search - fish                    268 non-null    int64
 43  Article Text Search - invasive                268 non-null    int64
 44  Article Text Search - diversion               268 non-null    int64
 45  Article Text Search - water diversion         268 non-null    int64
 46  Article Text Search - instream                268 non-null    int64
 47  Article Text Search - aquatic                 268 non-null    int64
dtypes: float64(6), int64(21), object(21)
memory usage: 100.6+ KB

### String Accessor for pandas.series

In [6]:
import numpy as np
import pandas as pd 

# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: object

In [7]:
# str accessor (doesn't do anything by itself)
s.str

In [8]:
# Use str accessor with additional methods to perform string operations
# .split splits strings by ';' and expands output into separate columns
s.str.split(';', expand=True)

            0        1
0  California   Nevada
1     Arizona     None
2         NaN      NaN
3      Nevada     Utah

In [12]:
# Use stack() method to flatten the data frame into a series
# default is to drop NAs and None from result
d = s.str.split(';', expand=True).stack()

### Examine the state codes

In [26]:
df['State']

0          CO
1          CO
2          UT
3         NaN
4         NaN
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 268, dtype: object

### Exploratory Wrangling

In [27]:
# Select the State column from the df data frame
df["State"]

0          CO
1          CO
2          UT
3         NaN
4         NaN
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 268, dtype: object

In [31]:
# Split the strings in the column by the delimeter ; into different columns
df["State"].str.split(";", expand = True)

       0     1     2     3     4     5     6
0     CO  None  None  None  None  None  None
1     CO  None  None  None  None  None  None
2     UT  None  None  None  None  None  None
3    NaN   NaN   NaN   NaN   NaN   NaN   NaN
4    NaN   NaN   NaN   NaN   NaN   NaN   NaN
..   ...   ...   ...   ...   ...   ...   ...
263   CO  None  None  None  None  None  None
264   CO  None  None  None  None  None  None
265   AZ    CA  None  None  None  None  None
266   AZ  None  None  None  None  None  None
267   AZ  None  None  None  None  None  None

[268 rows x 7 columns]

In [30]:
# Stack the results of the resulting data frame into a single pandas.Series
df["State"].str.split(";", expand = True).stack()

0    0     CO
1    0     CO
2    0     UT
5    0     AZ
11   0     OH
         ...
264  0     CO
265  0     AZ
     1     CA
266  0     AZ
267  0     AZ
Length: 230, dtype: object

In [32]:
# Find the unique string values in the resulting series
df["State"].str.split(";", expand = True).stack().unique()

array(['CO', 'UT', 'AZ', 'OH', ' UT', ' CO', ' NM', 'CA', ' NV', ' WY',
       ' CA', ' AZ', 'NV', 'NM', 'WY', 'TX'], dtype=object)

### Find unique state codes

In [33]:
# Update your code to obtain a list of codes (without repetition) of the states mentioned 
# in the news articles about water conflicts in the Colorado River Basin. 
# Hint: str.strip().

df["State"].str.split(";", expand = True).stack().str.strip().unique()

array(['CO', 'UT', 'AZ', 'OH', 'NM', 'CA', 'NV', 'WY', 'TX'], dtype=object)

In [34]:
#Bonus: How many articles mention each state?

df["State"].str.split(";", expand = True).stack().str.strip().value_counts()

AZ    87
CO    45
UT    40
NV    19
CA    16
NM    13
WY     8
OH     1
TX     1
dtype: int64